resources:
  - ../../base

namespace: prod

configMapGenerator:
  - name: app-two-html
    files:
      - index.html

generatorOptions:
  disableNameSuffixHash: true

patchesStrategicMerge:
  - replicas-patch.yaml
