apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-two
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-two
  template:
    metadata:
      labels:
        app: app-two
    spec:
      containers:
      - name: app-two
        image: ""
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
            ephemeral-storage: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts: []
      automountServiceAccountToken: false
